spring:
  cloud:
    gateway:
      actuator:
        enabled: true
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/user-service/api/v1/**
            - id: asset-service
              uri: lb:http://ASSET-SERVICE
              predicates:
                - Path=/asset-service/api/v1/**
            - id: post-service
              uri: lb:http://POST-SERVICE
              predicates:
                - Path=/post-service/api/v1/**

  main:
    web-application-type: reactive
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
    reactor.netty: INFO
server:
  port: 9292
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway