# file: user-service.yml (trong config server)
server:
  port: 8082
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 50MB
    context-path: /asset-service


spring:
  cloud:
    discovery:
      enabled: true
  data:
    mongodb:
      authentication-database: admin
      database: ${DB_ASSET_MONGO}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: ${MONGO_HOST}
      port: 27017


grpc:
  client:
    userServiceGrpc:
      address: "static://localhost:9091"
      negotiationType: PLAINTEXT
    postServiceGrpc:
      address: "discovery:///post-service"
      negotiationType: PLAINTEXT
    uploadServiceGrpc:
      address: "static://localhost:9092"
      negotiationType: PLAINTEXT
  server:
    port: 9093
    enable-reflection: true