# file: user-service.yml (trong config server)
server:
  port: 8083
  servlet:
    context-path: /post-service

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/tland_postdb
    username: root
    password: 090224@Tan
  jpa:
    properties:
      hibernate:
        format_sql: true


grpc:
  client:
    assetServiceGrpc:
      address: "discovery:///asset-service"
      negotiationType: PLAINTEXT
    userServiceGrpc:
      address: "discovery:///user-service"
      negotiationType: PLAINTEXT
    paymentServiceGrpc:
      address: "discovery:///payment-service"
      negotiationType: PLAINTEXT

  server:
    port: 9094
    enable-reflection: true
