server:
  port: 8085
  servlet:
    context-path: /search-service

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 50MB
  elasticsearch:
    uris: ${ES_SERVER}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
    index-recovery:
      mode: full # Make sure recovery mode is set to full
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org:
      elasticsearch:
        client: TRACE
      springframework:
        data:
          elasticsearch:
            client: TRACE

grpc:
  client:
    postServiceGrpc:
      address: "discovery:///post-service"
      negotiationType: PLAINTEXT

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
