# file: user-service.yml (trong config server)
server:
  port: 8081
  servlet:
    context-path: /user-service

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/tland_userdb
    username: root
    password: 090224@Tan
  jpa:
    properties:
      hibernate:
        format_sql: true
