# file: user-service.yml (trong config server)
server:
  port: 8081
  servlet:
    context-path: /user-service

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 50MB
  datasource:
    url: ${DB_USER_SERVICE_URL}
    username: ${DB_USER_SERVICE_USERNAME}
    password: ${DB_USER_SERVICE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true

grpc:
  client:
    uploadServiceGrpc:
      address: "static://localhost:9092"
      negotiationType: PLAINTEXT
  server:
    port: 9091
    enable-reflection: true

keycloak:
  auth-server-url: http://localhost:8443
  realm: TLand
  admin:
    client-id: admin-cli
    username: admin
    password: admin