dotenv:
  enabled: true

server:
  port: 8888
spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations